### ISSUE TITLE
Fonts need to be more fully specified

### ISSUE THREAD

**Issue by Gavin-McLeod** [bcgov-c/Gov-2.0-Bootstrap-Skeleton#3]
Default Myriad Pro font is provided only as a TTF. While most browsers can handle the web font specification, Internet Explorer expects appropriate MIME type configuration. Without that the site reverts to _Calibri, Arial, 'sans serif'_, rather than an alternative Myriad Pro web-font filetype. Properly, there should be access to EOT, WOFF, WOFF2, TTF, SVG font file types if possible.

As it is, a deployment of this skeleton to government application sites will otherwise require MIME type entries for over 90 applications for the Transportation Ministry alone. Can this be addressed at source instead?

ERROR Addressed:
CSS3114: @font-face failed OpenType embedding permission check. Permission must be Installable.

**Comment by juhewitt** [comment]
Hey Gavin!  I'll ask our graphics department about those other font formats. As for the MIME Type configuration, as per your point, this template is generic on purpose for scalability; trying to keep it as minimal as possible as other ministries won't want the overhead and more control specific to their builds.  For example, why the majority of the JS has been removed...

**Comment by Gavin-McLeod** [comment]
Justin, thanks.  
This has really nothing to do with JS, It should just be a few more lines to the main.css and inclusion of the alternative web font formats for Myriad Web Pro.   Also, keep in mind that IE does not support TTF web fonts prior to version 9.  We would do this ourselves but this font is licensed from Adobe so we can't acquire those files ourselves.  IE asks the server for TTF files using certain parameters different from other browsers, so the workaround would be a MIME entry to support that request.  That MIME entry would need to be applied for all applications using this package.  

Rather than a workaround that is imposed on all consumers of this package, let's complete the work and adhere to full standards by cleaning this up.  See https://www.w3.org/Fonts/

**Comment by juhewitt** [comment]
Hey Gavin!

I've uploaded the other font types made available to me that we have licence to use.  Do you have any particular preference for the CSS declarations?  As a community resource, I'll leave it up to those that fork this one to decide.  Here's some [reading](https://css-tricks.com/snippets/css/using-font-face/) I looked into with a quick google.

Cheers, 
J

**Comment by Gavin-McLeod** [comment]
I’ll refresh my fork and let our devs have a say.

Gavin McLeod
250-896-4437 (Cell)
778-698-3014 (Desk, Lync)

________________
User Experience / Information Architect
    Enterprise Architecture Services
    Information Management Branch
    Ministry of Transportation and Infrastructure
[cid:image001.png@01D2982A.650AF130]
